config/routes.rb
Rails.application.routes.draw do
 
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  devise_scope :customer do
    post '/customers/sign_up', to: 'public/registrations#create', as: 'custom_registration'
  end
    


  root to: "public/items#top"

  scope module: 'customers' do
    resources :items, only: [:show, :index]
    get 'about' => 'items#about'
   end
  

namespace :public do
    # resources :genres, only: [:show]
    patch 'customers/withdraw' => 'customers#withdraw', as: 'withdraw_customer'#退会
    get '/my_page', to: 'customers#show', as: 'my_page'#マイページ
    resources :my_page, only: [:show]
    get 'customers/edit' => 'customers#edit'
    patch 'update' => 'customers#update'
    get 'quit' => 'customers#quit'#退会画面
    get 'orders/about' => 'orders#about', as: 'orders_about'#注文情報入力
    # post 'orders/confirm' => 'orders#new', as: 'confirm_order'#注文情報確認
    get 'orders/thanks' => 'orders#thanks', as: 'thanks_order'#サンクス
    resources :items, only: [:index, :show]
    resources :orders, only: [:new, :create, :index, :show]#注文情報確認、注文履歴一覧、注文履歴詳細
    resources :cart_items, only: [:index, :create, :update, :destroy]
    # resources :customers, only: [:new, :create, :edit, :update]
    delete 'cart_items' => 'cart_items#all_destroy', as: 'all_destroy'
    get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'confirm_unsubscribe'
  end

  # root to: 'homes#top'
  # get 'about' => 'homes#about', as: 'about'
  # get '/admin', to: 'admin#top'
  # resources :admins
  # resources :items, only: [:index, :destroy, :edit, :show, :edit]
  # resources :customers, only: [:index, :show, :edit, :update]
  
  #devise_for :public_items
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #devise_for :admin_items
  
  # root to: "homes#top"
  # get '/about'=>'homes#about', as:'about'
  # get '/customers/:id', to: 'customers#show'
  # get '/customers/information/edit', to: 'customers#edit'
  # patch '/customers/information', to: 'customers#update'
  # get 'edit/:id' => 'public/customers#edit'
  
  devise_for :admins, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  
  namespace :admin do
    root :to => 'homes#top'
    resources :customers, only: [:index, :show, :edit, :update]
    resources :items, only: [:show, :index, :new, :create, :edit, :update, :destroy]
    resources :orders, only: [:index, :show, :update]
    resources :order_items, only: [:update]
    delete 'items'=> 'items#destroy'
  end
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items
  has_many :order_details
  #attr_accessor :authenticity_token
  has_one_attached :image
  validates :name, {presence: true}
  validates :introduction, {presence: true}
  validates :price, {presence: true}
  
  #消費税
  def with_tax_price
    (price * 1.1).floor
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
    #has_one_attached :image
    before_action :authenticate_admin!, only: [:create,:edit,:update,:index, :show, :new]
    
    def show
        @item=Item.find(params[:id])
        @cart_item = CartItem.new
        # @genres=Genre.all
    end
    
    def index
        @search=Item.ransack(params[:q])
        @items=@search.result.page(params[:page]).per(10)
    end
    

    def new
        @items=Item.new
        # @genre=[["ケーキ"], ["焼き菓子"], ["プリン"]]
        # @genres=Genre.all
        @active=[["販売中","false"], ["販売停止中","true"]]
    end
    
    def create
        @item = Item.new(item_params)
        #@item.customer_id = current_customer.id
        if @item.save!
            redirect_to admin_item_path(@item)
        else
            redirect_to new_admin_item_path
        end
    end

    def edit
        @item=Item.find(params[:id])
        @active=[["販売中","false"], ["販売停止中","true"]]
    end
    
    def update
        @item=Item.find(params[:id])
        if @item.update(item_params)
            redirect_to admin_items_path(@item)
            flash[:notice_update]="商品情報を更新しました"
        else
            redirect_to edit_admin_items_path(@item)
        end
    end
    
    def destroy
        @item=Item.find(params[:id])
        @item.destroy
        flash.now[:alert]="#{@item.name}を削除しました"
        redirect_to admin_items_path
    end
    
private
    def item_params
        params.require(:item).permit(:name, :introduction, :price, :image, :is_active)  
    end
end

app/views/admin/items/edit.html.erb
<!DOCTYPE html>
<html lang="ja">
<html class="fontawesome-i2svg-active fontawesome-i2svg-complete">
    <head></head>
    <main>
        <header>
        </header>
        <body>
          <div class="row">
          <div class="col-xs-10 col-xs-10 col-xs-offset-1">
            <div class="row">
            <%= form_with model: @item, url: admin_item_path do |f| %>
            
            <div class="col-xs-5">
             <h2>商品編集</h2>
             
              <div class= "item-new-form">
                <%= f.file_field :image, accept: "image/*" %>
              </div>
              <div class="product-img" style="margin-top: 20px;">
                <%= image_tag @item.image, size: "300x200" %>
              </div>
            </div>
            
            <div class="col-xs-5 col-xs-offset-2">
              <table class="table table-hover table-inverse">
                <tbody>
                  <tr>
                    <th>商品名</th>
                    <td><%= f.text_field :name, class: "form-control" %></td>
                  </tr>
                  <tr>
                    <th>商品説明</th>
                    <td><%= f.text_area :introduction, class: "form-control" %></td>
                  </tr>
                  <tr>
                    <th>販売価格</h4>
                    <td><%= f.text_field :price, class: "form-control" %></th>
                  </tr>
                  <tr>
                    <th>販売ステータス</th>
                    <td><%= f.select :is_active, @active, include_blank: "選択してください" %></td>
                  </tr>
                </tbody>
              </table>
              <div class="text-right">
                <%= f.submit "編集する", class: "btn btn-primary text-right" %>
              </div>
            </div>
            <% end %>
            <div class="text-right">
                <%= link_to "削除する", admin_item_path(@item), method: :delete, class: "btn btn-danger" %>
            </div>
          </div>
          </div>
        </body>
    </main>
</html>

app/views/admin/items/index.html.erb
<!DOCTYPE html>
<html lang="ja">
<html class="fontawesome-i2svg-active fontawesome-i2svg-complete">
    <main>
        <header>
            <div class="pull-right" style="margin-bottome: 10px;">
              <%= search_field(@search, url:public_items_path) do |f| %>
                <%= f.label :name, "キーワード" %>
                <%= f.search_field :name_cont %>
                <%= f.submit %>
              <% end %>
            </div>
        </header>
        <body>
            <div class="row">
                <div class="col-xs-10 col-xs-10 col-xs-offset-1">
                    <h2>商品一覧</h2>
                    <div class="text_right">
                        <%= link_to "新規登録", new_admin_item_path, class:"btn btn_-lg btn-primary" %>
                    </div>
                    <table class="table table-hover table-inverse">
                        <thead>
                            <tr>
                               <th>商品ID</th>
                               <th>商品名</th>
                               <th>税込価格</th>
                               <th>ステータス</th>
                            </tr>
                        </thead>
                           
                        <tbody>
                            <% @items.each do |item| %>
                                <tr>
                                    <td><%= item.id %></td>
                                    <td><%= link_to item.name, admin_item_path(item) %></td>
                                    <td>¥<%= item.price.to_s(:delimited, delimiter: ',') %></td>
                                    <td>
                                        <% if item.is_active == false %>
                                            販売中
                                        <%else%>
                                            販売停止中
                                        <%end%>
                                    </td>
                                </tr>
                            <%end%>
                            <%= paginate @items %>
                        </tbody>
                    </table>
                </div>
            </div>
        </body>
    </main>
</html>

app/views/admin/items/new.html.erb
<!DOCTYPE html>
<html lang="ja">
<html class="fontawesome-i2svg-active fontawesome-i2svg-complete">
  <main>
      <header>
        <div class="pull-right" style="margin-bottome: 10px;">
          <%= search_field(@search, url:public_items_path) do |f| %>
            <%= f.label :name, "キーワード" %>
            <%= f.search_field :name_cont %>
            <%= f.submit %>
          <% end %>
         </div>
      </header>
      <body>
        <div class="row">
        <div class="col-md-10 col-md-offset-1 col-xs-10 col-xs-offset-1">
          
            <div class="row">
            <%= form_with model: @items, url: admin_items_path, method: :post do |f| %>
            
            <div class="col-md-5 col-xs-5">
             <h1>商品新規登録</h1>
             
              <div class="item_new_form">
                <%= f.file_field :image, accept: "image/*" %>
              </div>
              <div class="product-img" style="margin-top: 20px;">
                <%= image_tag 'no_image.jpg', id:"file-preview", :size => '350×350' %>
              </div>
            </div>
            
            <div class="col-md-5 col-md-offset-2 col-xs-5 col-xs-offset-2">
              <table class="new-form-table">
                <tbody>
                  <tr>
                    <th>商品名</th>
                    <td><%= f.text_field :name %></td>
                  </tr>
                  <tr>
                    <th>商品説明</th>
                    <td><%= f.text_area :introduction %></td>
                  </tr>
                  <tr>
                    <th>販売価格</th>
                    <td><%= f.text_field :price %></td>
                  </tr>
                  <tr>
                    <th>販売ステータス</th>
                    <td><%= f.select :is_active, @active, include_blank: "選択してください" %></td>
                  </tr>
                </tbody>
              </table>
              
              <div class="text-right">
              <%= f.submit '新規登録' %>
              </div>
              </div>
          <% end %>
        </div>
        </div>
      </body>
  </main>

app/views/admin/items/show.html.erb
<!DOCTYPE html>
<html lang="ja">
<html class="fontawesome-i2svg-active fontawesome-i2svg-complete">
    <main>
      <body>
        <div class="row">
          <h2>商品詳細</h2>
          <% if @item.image.attached? %>
              <%= image_tag @item.image, size: "300x200" %>
          <% else %>
              <%= image_tag 'no_image', size: "300x200" %>
          <% end %>
        </div>
        
        <div class="col-xs-8">
          <table class="table table-hover table-inverse">
            <tbody>
              <tr>
                <td>商品名</td>
                <td><%= @item.name %></td>
              </tr>
              <tr>
                <td>商品説明</td>
                <td><%= @item.introduction %></td>
              </tr>
              <tr>
                <td>税込価格</td>
                <td>¥<%= @item.price %></td>
              </tr>
              <tr>
                <td>販売ステータス</td>
                <td>
                <% if @item.is_active == false %>
                販売中
                <%else%>
                販売停止中
                <%end%>
                </td>
              <tr>
            </tbody>
          </table>
          <div class="col-md-offset-1 col-md-2 text-right">
            <%= link_to "編集する" ,edit_admin_item_path(@item), class: "btn btn-primary" %>
          </div>
        </div>
        </div>
      </body>
    </main>
</html>