config/routes.rb
Rails.application.routes.draw do
 
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  devise_scope :customer do
    post '/customers/sign_up', to: 'public/registrations#create', as: 'custom_registration'
  end
    


  root to: "public/items#top"

  scope module: 'customers' do
    resources :items, only: [:show, :index]
    get 'about' => 'items#about'
   end
  

namespace :public do
    # resources :genres, only: [:show]
    patch 'customers/withdraw' => 'customers#withdraw', as: 'withdraw_customer'#退会
    get '/my_page', to: 'customers#show', as: 'my_page'#マイページ
    resources :my_page, only: [:show]
    get 'customers/edit' => 'customers#edit'
    patch 'update' => 'customers#update'
    get 'quit' => 'customers#quit'#退会画面
    get 'orders/about' => 'orders#about', as: 'orders_about'#注文情報入力
    # post 'orders/confirm' => 'orders#new', as: 'confirm_order'#注文情報確認
    get 'orders/thanks' => 'orders#thanks', as: 'thanks_order'#サンクス
    resources :items, only: [:index, :show]
    resources :orders, only: [:new, :create, :index, :show]#注文情報確認、注文履歴一覧、注文履歴詳細
    resources :cart_items, only: [:index, :create, :update, :destroy]
    # resources :customers, only: [:new, :create, :edit, :update]
    delete 'cart_items' => 'cart_items#all_destroy', as: 'all_destroy'
    get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'confirm_unsubscribe'
  end

  # root to: 'homes#top'
  # get 'about' => 'homes#about', as: 'about'
  # get '/admin', to: 'admin#top'
  # resources :admins
  # resources :items, only: [:index, :destroy, :edit, :show, :edit]
  # resources :customers, only: [:index, :show, :edit, :update]
  
  #devise_for :public_items
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #devise_for :admin_items
  
  # root to: "homes#top"
  # get '/about'=>'homes#about', as:'about'
  # get '/customers/:id', to: 'customers#show'
  # get '/customers/information/edit', to: 'customers#edit'
  # patch '/customers/information', to: 'customers#update'
  # get 'edit/:id' => 'public/customers#edit'
  
  devise_for :admins, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  
  namespace :admin do
    root :to => 'homes#top'
    resources :customers, only: [:index, :show, :edit, :update]
    resources :items, only: [:show, :index, :new, :create, :edit, :update, :destroy]
    resources :orders, only: [:index, :show, :update]
    resources :order_items, only: [:update]
    delete 'items'=> 'items#destroy'
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_items

  enum payment_methods: { "クレジットカード": 0, "銀行振込": 1 }
  enum order_status: { "入金待ち": 0, "入金確認": 1, "製作中": 2, "発送準備中": 3, "発送済み": 4 }
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
    before_action :authenticate_admin!
    
    def index
        @search=Order.ransack(params[:q])
        @orders=@search.result.page(params[:page]).per(20)
    end
    
    def show
        @order=Order.find(params[:id])
        @order_items=@order.order_items
    end
    
    def update
        order=Order.find(params[:id])
        order_items=order.order_items
        order.update(order_params)
            if order.order_status=="入金確認"
                order_items.update_all(making_status: "製作中")
            end
            redirect_to admins_order_path(order.id)
    end
    
    private
        def order_params
            params.require(:order).permit(:order_status)
        end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/index.html.erb
<!DOCTYPE html>
<html lang="ja">
<html class="fontawesome-i2svg-active fontawesome-i2svg-complete">
    <head></head>
    <main>
        <body>
              <div class="row">
                  <div class="col-xs-10 col-xs-offset-1">
                      <h2>注文一覧</h2>
                        <div class="order-table">
                            <table class="table table-hover table-inverse">
                                <thead>
                                    <tr>
                                        <th>購入日時</th>
                                        <th>購入者</th>
                                        <th>注文個数</th>
                                        <th>注文ステータス</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <% @orders.each do |order| %>
                                        <tr>
                                            <td><%= link_to order.created_at.strftime("%Y-%m-%d %H:%M:%S"), admin_order_path(order) %></td>
                                            <td><%= order.customer.last_name + "　" + order.customer.first_name %></td>
                                            <td><%= order.order_items.sum(:quantity) %></td>
                                            <td><%= order.order_status %></td>
                                        </tr>
                                    <%end%>
                                    <%= paginate @orders %>
                                </tbody>
                            </table>
                        </div>
                  </div>
              </div>
        </body>
    </main>
</html>

app/views/admin/orders/show.html.erb
<!DOCTYPE html>
<html lang="ja">
<html class="fontawesome-i2svg-active fontawesome-i2svg-complete">
    <head></head>
    <main>
        <body>
            <div class="col-xs-10 col-xs-offset-1">
                <div class="row">
                    <div class="col-xs-7">
                    <h2>注文詳細</h2>
                    <table class="table table-bordered table-condensed">
                        <tbody>
                            <tr>
                                <th>購入者</th>
                                <td><%= link_to admin_customer_path(@order.customer) do %>
                                <%= @order.customer.last_name %>
                                <%= @order.customer.first_name %>
                                <% end %>
                                </td>
                            </tr>
                            <tr>
                                <th>購入日時</th>
                                <td><%= @order.created_at.strftime("%Y-%m-%d %H:%M:%S") %></td>
                            </tr>
                            <tr>
                                <th>配送先</th>
                                <td>〒<%= @order.postal_code %> <%= @order.address %></td>
                            </tr>
                            <tr>
                                <th>支払方法</th>
                                <td><%= @order.payment_methods %></td>
                            </tr>
                            <tr>
                                <th>注文ステータス</th>
                                <td><%= form_with model: @order, url: admin_order_path(@order) do |f| %>
                                <%= f.select :order_status, Order.order_statuses.keys.to_a %>
                                <%= f.submit "更新する", class: "btn btn-success" %>
                                <% end %>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <div class="col-xs-7 order-items">
                    <table class="table table-bordered table-condensed">
                        <thead>
                            <tr>
                                <th>商品名</th>
                                <th>注文時商品価格(税込)</th>
                                <th>個数</th>
                                <th>小計</th>
                                <th>製作ステータス</th>
                            </tr>
                        </thead>
                        <tbody>
                            <% @order_items.each do |order_item| %>
                            <tr>
                                <td><%= order_item.item.name %></td>
                                <td>¥<%= (order_item.price).floor.to_s(:delimited, delimiter: ',') %></td>
                                <td><%= order_item.quantity %></td>
                                <td>¥<%= (order_item.price * order_item.quantity).floor.to_s(:delimited, delimiter: ',') %></td>
                                <td>
                                    <%= form_with model: @order_item, url: admin_order_item_path(order_item) do |f|  %>
                                    <%= f.select :making_status, OrderItem.making_statuses.keys.to_a %>
                                    <%= f.submit '更新',class:"btn btn-success" %>
                                    <% end %>
                                </td>
                            </tr>
                            <%end%>
                        </tbody>
                    </table>
                    </div>
                </div>
                <div class="col-xs-3 billing">
                    <table class="table table-bordered table-condensed">
                        <tbody>
                            <tr>
                                <th>商品合計</th>
                                <td>¥<%= (@order.billing_amount - @order.postage).to_s(:delimited, delimiter: ',') %></td>
                            </tr>
                            <tr>
                                <th>送料</th>
                                <td>¥<%= @order.postage.to_s(:delimited, delimiter: ',') %></td>
                            </tr>
                            <tr>
                                <th>請求合計金額</th>
                                <td>¥<%= @order.billing_amount.to_s(:delimited, delimiter: ',') %></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </body>
    </main>
</html>