config/routes.rb
Rails.application.routes.draw do
 
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  devise_scope :customer do
    post '/customers/sign_up', to: 'public/registrations#create', as: 'custom_registration'
  end
    


  root to: "public/items#top"

  scope module: 'customers' do
    resources :items, only: [:show, :index]
    get 'about' => 'items#about'
   end
  

namespace :public do
    # resources :genres, only: [:show]
    patch 'customers/withdraw' => 'customers#withdraw', as: 'withdraw_customer'#退会
    get '/my_page', to: 'customers#show', as: 'my_page'#マイページ
    resources :my_page, only: [:show]
    get 'customers/edit' => 'customers#edit'
    patch 'update' => 'customers#update'
    get 'quit' => 'customers#quit'#退会画面
    get 'orders/about' => 'orders#about', as: 'orders_about'#注文情報入力
    # post 'orders/confirm' => 'orders#new', as: 'confirm_order'#注文情報確認
    get 'orders/thanks' => 'orders#thanks', as: 'thanks_order'#サンクス
    resources :items, only: [:index, :show]
    resources :orders, only: [:new, :create, :index, :show]#注文情報確認、注文履歴一覧、注文履歴詳細
    resources :cart_items, only: [:index, :create, :update, :destroy]
    # resources :customers, only: [:new, :create, :edit, :update]
    delete 'cart_items' => 'cart_items#all_destroy', as: 'all_destroy'
    get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'confirm_unsubscribe'
  end

  # root to: 'homes#top'
  # get 'about' => 'homes#about', as: 'about'
  # get '/admin', to: 'admin#top'
  # resources :admins
  # resources :items, only: [:index, :destroy, :edit, :show, :edit]
  # resources :customers, only: [:index, :show, :edit, :update]
  
  #devise_for :public_items
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #devise_for :admin_items
  
  # root to: "homes#top"
  # get '/about'=>'homes#about', as:'about'
  # get '/customers/:id', to: 'customers#show'
  # get '/customers/information/edit', to: 'customers#edit'
  # patch '/customers/information', to: 'customers#update'
  # get 'edit/:id' => 'public/customers#edit'
  
  devise_for :admins, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  
  namespace :admin do
    root :to => 'homes#top'
    resources :customers, only: [:index, :show, :edit, :update]
    resources :items, only: [:show, :index, :new, :create, :edit, :update, :destroy]
    resources :orders, only: [:index, :show, :update]
    resources :order_items, only: [:update]
    delete 'items'=> 'items#destroy'
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         has_many :cart_items, dependent: :destroy
         has_many :orders, dependent: :destroy
         has_many :shipping_addresses, dependent: :destroy
         has_one_attached :image
         
    def active_for_authentication?
      super && (self.is_deleted == false)
    end
    
       validates :last_name,  presence: true
       validates :first_name, presence: true
       validates :last_name_kana,  presence: true
       validates :first_name_kana, presence: true
       validates :telephone_number, presence: true
       validates :postal_code,  presence: true
       validates :address, presence: true
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
    # def new
    #   @customer=Customer.new
    # end
    
    # def create
    #   @customer = Customer.new(customer_params)
    #   @customer.id = current_customer.id
    #   @customers= Customer.all
    #   if @customer.save
    #     redirect_to customer_path
    #   else
    #     render :new
    #   end
    # end  
    def index #会員一覧
      @search=Customer.ransack(params[:q])
      @customers=@search.result.page(params[:page])
    end
    
    def show
      @customer=Customer.find(params[:id])
    end
    
    def edit
      @customer=Customer.find(params[:id])
    end
    
    def update
      @customer=Customer.find(params[:id])
      if @customer.update(customer_params)
        flash[:notice_update] ="会員情報を更新しました"
        redirect_to admin_customer_path(@customer)
      else
        render edit_admin_customer_path(@customer)
      end
    end
    
  private
    def customer_params
      params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_deleted)
    end
end

app/views/customers/edit.html.erb
<!DOCTYPE html>
<html lang="ja">
<html class="fontawesome-i2svg-active fontawesome-i2svg-complete">
    <head></head>
    <body>
        <main>
            <%= form_with model: @customer do |f| %>
                <h3>会員情報編集</h3>
                <p>氏名</p><%= f.text_field :last_name %><%= f.text_field :first_name %>
                <p>フリガナ</p><%= f.text_field :last_name_kana %><%= f.text_field :first_name_kana %>
                <p>郵便番号</p><%= f.text_field :postal_code %>
                <p>住所</p><%= f.text_field :address %>
                <p>電話番号</p><%= f.text_field :telephone_number %>
                <p>メールアドレス</p><%= f.text_field :email %>
                <%= f.submit '編集内容を保存' %>
                <%= f.submit '退会' %>
            <%end%>
        </main>
    </body>
</html>

app/views/customers/show.html.erb
<!DOCTYPE html>
<html lang="ja">
<html class="fontawesome-i2svg-active fontawesome-i2svg-complete">
    <body>
        <main>
            <div>
              <%= flash[:notice] %>
            </div>
            <div>
                <h3>マイページ</h3>
                <h3>登録情報</h3><%= link_to "編集する", edit_customer_registration_path, class: 'btn btn-default' %>
                <table border="1">
                    <tr>
                        <td>氏名</td>
                        <td><%= @customer.first_name %> <%= @customer.last_name %></td>
                    </tr>
                    <tr>
                        <td>カナ</td>
                        <td><%= @customer.first_name_kana %> <%=@customer.last_name_kana %></td>
                    </tr>
                    <tr>
                        <td>郵便番号</td>
                        <td><%= @customer.postal_code %></td>
                    </tr>
                    <tr>
                        <td>住所</td>
                        <td><%= @customer.address %></td>
                    </tr>
                    <tr>
                        <td>電話番号</td>
                        <td><%= @customer.telephone_number %></td>
                    </tr>
                    <tr>
                        <td>メールアドレス</td>
                        <td><%= @customer.email %></td>
                    </tr>
                </table>
                <h3>配送先</h3><%= link_to "一覧を見る",  class: 'btn btn-default' %>
                <h3>注文履歴</h3><%= link_to "一覧を見る",  class: 'btn btn-default' %>
            </div>
        </main>
    </body>
</html>

app/views/customers/withdraw.html.erb
<!DOCTYPE html>
<html lang="ja">
<html class="fontawesome-i2svg-active fontawesome-i2svg-complete">
    <body>
        <main>
            <div>
                <h4>本当に退会しますか？</h4>
                <p>
                    退会すると、会員登録情報や
                    これまでの購入記録が閲覧できなくなります。
                    退会する場合は、「退会する」をクリックしてください。
                </p>
            </div>
            <%= form_with model: @customer do |f| %>
                <%= f.submit '退会しない' %>
                <%= f.submit '退会する' %>
            <%end%>
        </main>
    </body>
</html>