config/routes.rb
Rails.application.routes.draw do
 
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  devise_scope :customer do
    post '/customers/sign_up', to: 'public/registrations#create', as: 'custom_registration'
  end
    


  root to: "public/items#top"

  scope module: 'customers' do
    resources :items, only: [:show, :index]
    get 'about' => 'items#about'
   end
  

namespace :public do
    # resources :genres, only: [:show]
    patch 'customers/withdraw' => 'customers#withdraw', as: 'withdraw_customer'#退会
    get '/my_page', to: 'customers#show', as: 'my_page'#マイページ
    resources :my_page, only: [:show]
    get 'customers/edit' => 'customers#edit'
    patch 'update' => 'customers#update'
    get 'quit' => 'customers#quit'#退会画面
    get 'orders/about' => 'orders#about', as: 'orders_about'#注文情報入力
    # post 'orders/confirm' => 'orders#new', as: 'confirm_order'#注文情報確認
    get 'orders/thanks' => 'orders#thanks', as: 'thanks_order'#サンクス
    resources :items, only: [:index, :show]
    resources :orders, only: [:new, :create, :index, :show]#注文情報確認、注文履歴一覧、注文履歴詳細
    resources :cart_items, only: [:index, :create, :update, :destroy]
    # resources :customers, only: [:new, :create, :edit, :update]
    delete 'cart_items' => 'cart_items#all_destroy', as: 'all_destroy'
    get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'confirm_unsubscribe'
  end

  # root to: 'homes#top'
  # get 'about' => 'homes#about', as: 'about'
  # get '/admin', to: 'admin#top'
  # resources :admins
  # resources :items, only: [:index, :destroy, :edit, :show, :edit]
  # resources :customers, only: [:index, :show, :edit, :update]
  
  #devise_for :public_items
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #devise_for :admin_items
  
  # root to: "homes#top"
  # get '/about'=>'homes#about', as:'about'
  # get '/customers/:id', to: 'customers#show'
  # get '/customers/information/edit', to: 'customers#edit'
  # patch '/customers/information', to: 'customers#update'
  # get 'edit/:id' => 'public/customers#edit'
  
  devise_for :admins, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  
  namespace :admin do
    root :to => 'homes#top'
    resources :customers, only: [:index, :show, :edit, :update]
    resources :items, only: [:show, :index, :new, :create, :edit, :update, :destroy]
    resources :orders, only: [:index, :show, :update]
    resources :order_items, only: [:update]
    delete 'items'=> 'items#destroy'
  end
end

app/views/layouts/_errors.html.erb
<!DOCTYPE html>
<html>
    <% if obj.errors.any? %>
        <div id="error_explanation">
            <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
            <ul>
                <% obj.errors.full_messages.each do |message| %>
                <li><%= message %></li>
                <% end %>
            </ul>
        <div>
    <% end %>
</html>

app/views/layouts/_footer.html.erb
<!DOCTYPE html>
<html>
    <footer>
        <div class="container">
          <div class="small text-center text-muted" style="margin: 50px 0;">minamino © 2023  nagano_cake
          </div>
        </div>
    </footer>
</html>

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<html>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <div class="container">
                    <a class="navbar-brand p-3" href="/" ><%= image_tag('img_logo.png', size: '140x29') %></a>
                    <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav ml-auto">
                        <% if customer_signed_in? %>
                         <li style="font-family: BatangChe; margin-top: 15px;">
                             ようこそ、<%= current_customer.last_name + current_customer.first_name %>さん
                         </li>
                         <li><%= link_to "マイページ", public_my_page_path, class: 'nav-link text-dark' %></li>
                         <li><%= link_to "商品一覧", public_items_path, class: 'nav-link text-dark' %></li>
                         <li><%= link_to "カート", public_cart_items_path, class: 'nav-link text-dark' %></li>
                         <li><%= link_to "About", about_path, class: 'nav-link text-dark' %></li>
                         <li><%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'nav-link text-dark' %></li>
                        <% elsif admin_signed_in? %>
                         <li><%= link_to "商品一覧", admin_items_path, class: 'nav-link text-dark' %></li>
                         <li><%= link_to "会員一覧", admin_customers_path, class: 'nav-link text-dark' %></li>
                         <li><%= link_to "注文一覧",admin_orders_path, class: 'nav-link text-dark' %></li>
                         <li><%= link_to "About", about_path, class: 'nav-link text-dark' %></li>
                         <li><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-dark' %></li>
                        <%else%>
                         <li><%= link_to "商品一覧", public_items_path, class: 'nav-link text-dark' %></li>
                         <li><%= link_to "新規登録", new_customer_registration_path, class: 'nav-link text-dark' %></li>
                         <li><%= link_to "About", about_path, class: 'nav-link text-dark' %></li>
                         <li><%= link_to "ログイン", new_customer_session_path, class: 'nav-link text-dark' %></li>
                        <%end%>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="fontawesome-i2svg-active fontawesome-i2svg-complete">
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/91859b3e97.js" crossorigin="anonymous"></script>
    <style type="text/css"></style>
    <title>NaganoCake</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
    <% if customer_signed_in? %>
  <body class="d-flex flex-column vh-100">
      <div class="shadow-sm">
        <%= render "layouts/header" %>
      </div>
      <div class="container">
        <%= yield %>
      </div>
      <%= render "layouts/footer" %>
      <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    </body>
  <% elsif admin_signed_in? %>
    <body class="d-flex flex-column vh-100">
      <div class="shadow-sm">
        <%= render "layouts/header" %>
      </div>
      <div class="container">
        <%= yield %>
      </div>
      <%= render "layouts/footer" %>
      <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    </body>
  <% else %>
    <body class="d-flex flex-column vh-100">
      <div class="shadow-sm">
        <%= render "layouts/header" %>
      </div>
      <div class="container">
        <%= yield %>
      </div>
      <%= render "layouts/footer" %>
      <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
  <% end %>
</html>